# This file is used to set default values for the Helm chart.
replicaCount: 1

name: taskapp

image:
  repository: ongeziwe17/taskapp
  tag: "9de34a5"

service:
  type: NodePort
  port: 80
  targetPort: 8080

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

imagePullPolicy: IfNotPresent

autoscaling:
  enabled: false
