# values.yaml
replicaCount: 1

name: taskapp

image:
  repository: ongeziwe17/taskapp
  tag: sha256-52d8257361c2e20c8ddccb8dc15f49a4537da480ddc4c9c43d3d5a35d9b5671c

service:
  type: NodePort
  port: 80

autoscaling:
  enabled: false
