---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    ConnectionStrings__DefaultConnection: AgAv4jQgKnz7qD4mavnsh2g1pyi+pqwm6UKP+8CDfdKIJF7xnXYVxHWhpB41acCZSNweECwq6CP0y/if9AfdrOKPl0MnqtDdvwRVAYJgWxsyN4eeVWVA3H4M47OTp7aKLhvEPsVLtse3+xNLvidFraumJ9/NXL/0sK0heBORlqQA4von2E25JvIWEjm9q+de1Vxa/MXhWXCuiSFtLt1d3M1rkrxN4/PQdJRmssIUtPMDWN0K1NLpIRXqOxQOentqdCSNNXE5qUfKJFQ1D21ihMRKDVzpVVAE2BRF6JPdVbc1wuAusLQ/3/pS7YSaRDt9gnUQUSxWe9JqPzzk2SeDgpwc70m9Sd91kEYs9sb0yyKNgEyAncosYM0/DsW1G3LzeNBOvqY9Uxl5bE197oEOkbGbODgMK5voN97GEQYZ5OQx7d3j2PzpdyOC88I+upvi3cBqFR1pVDjcYJhRUbi5j7t2XJ+CwY7PRo7TmR8dh+dRT0H3Sp55mi0YbFfy/UHP6RiOpKbcvieboMhtpekk5RKfgs1B3ZvvYzD5IghVW/NIXZvJFanc1x4w328YordB5B3cmZ+DyOclSa4ASyCNMA9xXAhCJD7+uawyBvofRPxlwqRoKSbCAlLlqbHS5DVRz1EG7nR4IKEW6bxJ2IzemIrmt0C2rOyeE/t8vvY8nSFxzpTf/kCYk6RshyURaAxWc3eBk+yE+I/ivzSjPuKnG/MJK2e+UHg5QV0nCKL9W6/vU2bImpdujsmcCFWY3NqJXDSm0yJeBXQ9tLqiCWVOYRUn50zasWp6+vev+I6tkIK386G40+FByZ+7HUmPWNx9G49ox2onE0WsuXIm9g==
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: {{ .Release.Namespace }}
