---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: taskapp
spec:
  encryptedData:
    ConnectionStrings__DefaultConnection: AgBLY4OPMRNNfmXAs4ler0+taXhvzs7Ti9MaMX9L8q/ZO+jFMywvKDNvSZ3xZH5KzqXIYmNese7WlC3Yi7QHduaGlN08797ZjZX+rNloMQ32nNzzSqk40o72xgjJ+ONq9uwcIrbWJv0fMwNil1KZpmzZPJIZOwWBV47vwsQK1srtd9EyBcbjVZZGKfyKp5HJwdbChI3E6pBS68bXm6pjDReEVN4pZjs1CPlEV/gXT8xwuW2I+8mZ97uEGRiWS6gINrbPKbzhDUogxFVhkuQY1+Rz+z172HGGjc3K4caqCb3mB0mpcc0OD7YKuLWBfsL7tOvrXutTU3dhkInzlxojHiaHzwKp/uEb47fFz52VpaxCCQqtIR7wuZq/pCcL3gsjw5Xt4AMkyzYS5PLcKpljObY+cwp9Y4R5MiHyoHeTILPGOuQaj2VqQylzWrCviWiUkuEcHgjMUvxifsU9UD3RY22CMDXR5mvGUE3QDsjDu3lIWwPgiAui+je5UB3Ltii8m9saWr/m4XycOgkddSLJtYZ2nPw+YsOrEIP7VPAb9Dmr1xDRwwuhpLckQt00orxrwUkzRq8hYlR+TE4OL0JmYuUn/pniuF4wF9lyvtsn1ToD1z5fwwaG2G5t556eXGKOAdqypPkcsP6/jyNRHX1QD8yBBfIIUn/M5/HOYN1/2CdKVhZ8bmZvuE5bbyThbGFMotnVvUJf7BCWp1HgxUbrqC3WlWZZfhMqHJvDJ3XyBz2+rlQ5BsipYUSl2CXBOT51SRmwD79GxSjEfU8EypHwg7kOxpFj2LopEUP4MQNier2fbypojKOWYnzhbaVQgw==
    SA_PASSWORD: AgAyU1euwsVSsF3p+HBVREC7KRzBt0XfDCRKHnSKISrQTTHRGJEU7UZtDGII8E4g5o7+tPn6k7rxUFllGS1L7V0ga0T2v4snlZ7Hj7y9ogX235wcdct2qwh8COQFSUUvpVUrOsYIl+yPi/Sx5YgPH1VeGKkiFQYXcA1vm6YLcNJHeQiuq5BbNW+FOgKfcXVEijJwzWPvmB+kfb282moPK8pjJ9ezjtuAohza4xvE8jUvOwvDc6Cv3y+Y5hVV4KxHyS4qPS/CTxqMSFTk+7yTRauSKhrm9r11dEd1kQ9WxKD+a2jParj1vELPnnDAZklOx+GC+OKC923eKbvUF/zzbguMqi05J7fsmPGfbtAPxGDJ3V7lzYQecmEq9UHHnnKqhg4VUoPo0GYysjLevQWL/OIIwVdY+24h6dlVyYc+Rns+D22shlrKfwqBjm5HNx2nL9BKzyhsoeXU1lvrQrvoEC1n5PddMQFWRQEFStzy4VSo0Z6yQKaZuYbLlXq9y0Aoh4ZaHd7NnHU5kT/pdRspuWovGZmKxO+fJM7RmAotGjMZiLnJzfALft3NbHlmaFqUUNzKQrLFbvmjuCu52obNl2NM1/OM/yD8RTD/I7hXr9k8KhG4HCEajk42laBvW6PVNkeuxGQgEfsO/zcpffmq6PEVX7XVh1NrKg8mgbDIcuKeGYy7xLa4qDKerR8rM1Hjt0Zqv2TUvreKn75TIk6U
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: taskapp
    type: Opaque
