# This file defines a Kubernetes Deployment and Service for SQL Server.
# It includes the SQL Server container, environment variables, and a service to expose it.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          resources:
            requests:
              memory: "800Mi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: SA_PASSWORD
            - name: MSSQL_PID
              value: "Developer"
          readinessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3